main:
	g++ -c -std=c++98 main.cpp     
	g++ -c -std=c++98 InputLayer.cpp     
	g++ -c -std=c++98 HiddenLayer.cpp  
	g++ -c -std=c++98 HiddenNeuron.cpp     
	g++ -c -std=c++98 NeuralNetwork.cpp    
	g++ -c -std=c++98 OutputLayer.cpp
	g++ -o main main.o InputLayer.o HiddenLayer.o HiddenNeuron.o NeuralNetwork.o OutputLayer.o 
	./main 
clean:     
	rm *.o main 