main:
	g++ -c -std=c++98 main.cpp     
	g++ -c -std=c++98 piece.cpp 
	g++ -c -std=c++98 board.cpp
	g++ -c -std=c++98 solver.cpp    
	g++ -o main main.o board.o piece.o solver.o
	./main 
clean:     
	rm *.o main 